"""erp_connections

Revision ID: 4df56e42c623
Revises: f511deb40a06
Create Date: 2026-04-14 20:32:35.179822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df56e42c623'
down_revision: Union[str, Sequence[str], None] = 'f511deb40a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('erp_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('integration_mode', sa.String(length=30), nullable=False),
    sa.Column('erp_base_url', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=30), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('sftp_host', sa.String(length=300), nullable=True),
    sa.Column('sftp_port', sa.Integer(), nullable=True),
    sa.Column('sftp_username', sa.String(length=100), nullable=True),
    sa.Column('sftp_path', sa.String(length=300), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_count', sa.Integer(), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_connections_tenant_id'), 'erp_connections', ['tenant_id'], unique=False)
    op.create_index('ix_erp_tenant_type', 'erp_connections', ['tenant_id', 'erp_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_user_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_erp_tenant_type', table_name='erp_connections')
    op.drop_index(op.f('ix_erp_connections_tenant_id'), table_name='erp_connections')
    op.drop_table('erp_connections')
    # ### end Alembic commands ###
