"""asp_submission_logs_and_vr_asp_fields

Revision ID: 8831ed63d225
Revises: 4df56e42c623
Create Date: 2026-04-15 09:13:35.774587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8831ed63d225'
down_revision: Union[str, Sequence[str], None] = '4df56e42c623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asp_submission_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('etl_job_id', sa.String(length=36), nullable=True),
    sa.Column('asp_name', sa.String(length=100), nullable=True),
    sa.Column('submission_id', sa.String(length=100), nullable=True),
    sa.Column('clearance_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_code', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asp_submission_logs_submitted_at'), 'asp_submission_logs', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_asp_submission_logs_tenant_id'), 'asp_submission_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_asp_submission_logs_validation_run_id'), 'asp_submission_logs', ['validation_run_id'], unique=False)
    op.create_index('ix_asp_tenant_date', 'asp_submission_logs', ['tenant_id', 'submitted_at'], unique=False)
    op.create_index('ix_asp_tenant_status', 'asp_submission_logs', ['tenant_id', 'status'], unique=False)
    op.add_column('validation_runs', sa.Column('asp_submission_id', sa.String(length=100), nullable=True))
    op.add_column('validation_runs', sa.Column('asp_clearance_id', sa.String(length=100), nullable=True))
    op.add_column('validation_runs', sa.Column('asp_status', sa.String(length=30), nullable=True))
    op.add_column('validation_runs', sa.Column('asp_rejection_reason', sa.Text(), nullable=True))
    op.add_column('validation_runs', sa.Column('asp_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('validation_runs', sa.Column('asp_latency_ms', sa.Float(), nullable=True))
    op.add_column('validation_runs', sa.Column('phase', sa.String(length=20), nullable=True))
    op.add_column('validation_runs', sa.Column('error_phase', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asp_tenant_status', table_name='asp_submission_logs')
    op.drop_index('ix_asp_tenant_date', table_name='asp_submission_logs')
    op.drop_index(op.f('ix_asp_submission_logs_validation_run_id'), table_name='asp_submission_logs')
    op.drop_index(op.f('ix_asp_submission_logs_tenant_id'), table_name='asp_submission_logs')
    op.drop_index(op.f('ix_asp_submission_logs_submitted_at'), table_name='asp_submission_logs')
    op.drop_table('asp_submission_logs')
    op.drop_column('validation_runs', 'error_phase')
    op.drop_column('validation_runs', 'phase')
    op.drop_column('validation_runs', 'asp_latency_ms')
    op.drop_column('validation_runs', 'asp_submitted_at')
    op.drop_column('validation_runs', 'asp_rejection_reason')
    op.drop_column('validation_runs', 'asp_status')
    op.drop_column('validation_runs', 'asp_clearance_id')
    op.drop_column('validation_runs', 'asp_submission_id')
    # ### end Alembic commands ###
