"""postgresql_initial_schema

Revision ID: f511deb40a06
Revises: 
Create Date: 2026-04-10 02:02:28.574185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f511deb40a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_index('ix_audit_user_action', 'audit_logs', ['username', 'action'], unique=False)
    op.create_table('etl_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('invalid_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etl_created', 'etl_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_etl_jobs_batch_id'), 'etl_jobs', ['batch_id'], unique=True)
    op.create_index(op.f('ix_etl_jobs_created_at'), 'etl_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_etl_jobs_tenant_id'), 'etl_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_etl_tenant_status', 'etl_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=10), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('etl_row_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('etl_job_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etl_job_id'], ['etl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_row_errors_etl_job_id'), 'etl_row_errors', ['etl_job_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('invoice_type_code', sa.String(length=10), nullable=True),
    sa.Column('seller_trn', sa.String(length=20), nullable=True),
    sa.Column('buyer_trn', sa.String(length=20), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('currency_code', sa.String(length=5), nullable=True),
    sa.Column('tax_category_code', sa.String(length=5), nullable=True),
    sa.Column('total_with_tax', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('pass_percentage', sa.Float(), nullable=True),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.Column('field_results_json', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('etl_job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etl_job_id'], ['etl_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_created_at'), 'validation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_validation_runs_etl_job_id'), 'validation_runs', ['etl_job_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_invoice_number'), 'validation_runs', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_validation_runs_is_valid'), 'validation_runs', ['is_valid'], unique=False)
    op.create_index(op.f('ix_validation_runs_tenant_id'), 'validation_runs', ['tenant_id'], unique=False)
    op.create_index('ix_vr_invoice_num', 'validation_runs', ['invoice_number', 'tenant_id'], unique=False)
    op.create_index('ix_vr_tenant_created', 'validation_runs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_vr_tenant_valid', 'validation_runs', ['tenant_id', 'is_valid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vr_tenant_valid', table_name='validation_runs')
    op.drop_index('ix_vr_tenant_created', table_name='validation_runs')
    op.drop_index('ix_vr_invoice_num', table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_tenant_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_is_valid'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_invoice_number'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_etl_job_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_created_at'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_etl_row_errors_etl_job_id'), table_name='etl_row_errors')
    op.drop_table('etl_row_errors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_etl_tenant_status', table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_tenant_id'), table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_created_at'), table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_batch_id'), table_name='etl_jobs')
    op.drop_index('ix_etl_created', table_name='etl_jobs')
    op.drop_table('etl_jobs')
    op.drop_index('ix_audit_user_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
